name: Sidharth's B-log
description: Idk
meta_description: "Sid's Blog"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'sidharthgoel.com' #blog
author:         'Sidharth Goel'
