# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sidharth Goel
tagline:          :)
url:              http://sidharthgoel.com
paginate:         1
baseurl:          /
author:
  name:           Sidharth Goel
  url:            https://sidharthgoel.com
  email:          me@sidharthgoel.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/sidharthgoel/sidharthgoel.github.io
