# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sidharth Goel
tagline:          'Programmer, Student'
url:              http://sidharthgoel.com
shorturl:         sidharthgoel.com

author:
  name:           'Sidharth Goel'
  url:            https://sidharthgoel.com

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/sidharthgoel/sidharthgoel.github.ios

# This is the list of pages to incldue in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
