name: Sid's B-log
description: Idk
meta_description: My Blog

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'sidharthgoel.com'
author:         'Sidharth Goel'
