name: Sid's Blog
description: Yeaaah
meta_description: "Sid's Blog"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'blog url'
author:         'Sidharth Goel'
